using System.Text;
using Soft.Compiler.Template;
using Soft.Compiler.Abstractions;

namespace Soft.Compiler.Emit.Generators;

/// <summary>
/// Generates slot content projection.
/// Handles @slot { } directive.
/// </summary>
public class SlotGenerator : INodeGenerator
{
    public bool CanGenerate(TemplateNode node)
    {
        return node is TemplateSlotDirective;
    }
    
    public string Generate(TemplateNode node, CodeGenerationContext context)
    {
        var slotNode = (TemplateSlotDirective)node;
        var code = new StringBuilder();
        var slotVar = context.NextVar();
        var slotName = slotNode.Name;
        
        code.AppendLine($"{context.Indent()}// Slot: {slotName}");
        code.AppendLine($"{context.Indent()}const {slotVar} = document.createElement('div');");
        code.AppendLine($"{context.Indent()}{slotVar}.setAttribute('data-slot', '{slotName}');");
        code.AppendLine($"{context.Indent()}");
        code.AppendLine($"{context.Indent()}// Render slot content");
        code.AppendLine($"{context.Indent()}if ((this as any).__slots && (this as any).__slots['{slotName}']) {{");
        code.AppendLine($"{context.Indent()}    (this as any).__slots['{slotName}'].forEach((child: Node) => {{");
        code.AppendLine($"{context.Indent()}        {slotVar}.appendChild(child.cloneNode(true));");
        code.AppendLine($"{context.Indent()}    }});");
        code.AppendLine($"{context.Indent()}}} else {{");
        code.AppendLine($"{context.Indent()}    // Fallback content");
        
        // Generate fallback content
        var fallbackContext = new CodeGenerationContext
        {
            ParentVar = slotVar,
            ClassName = context.ClassName,
            IndentLevel = context.IndentLevel,
            LoopVariables = context.LoopVariables
        };
        foreach (var child in slotNode.FallbackContent)
        {
            // Fallback content will be generated by orchestrator
        }
        
        code.AppendLine($"{context.Indent()}}}");
        code.AppendLine($"{context.Indent()}");
        code.AppendLine($"{context.Indent()}{context.ParentVar}.appendChild({slotVar});");
        
        return code.ToString();
    }
}
